### ISSUE TITLE
Docker image fails to start, endlessly restarts

### ISSUE THREAD

**Issue by LazerDickMcCheese** [Feramance/qBitrr#101]
What's wrong with the following docker compose? I'm pretty new to docker, but I thought this was going to be a simple set up.

version: "3"
services:
  qbitrr:
   image: feramance/qbitrr:latest
   user: 1000:1000 # Required to ensure the container is run as the user who has perms to see the 2 mount points and the ability to write to the CompletedDownloadFolder mount
   tty: true # Ensure the output of docker-compose logs qBitrr are properly colored.
   restart: unless-stopped
   environment:
    - TZ=America/New_York
   volumes:
    - /etc/localtime:/etc/localtime:ro
    - /volume1/docker/qbitrr/config:/config  # Config folder for qBitrr
    - /volume1/docker/qbittorrent/torrents/completed:/completed_downloads:rw
    
   logging:
    driver: "json-file"
    options:
     max-size: "50m"
     max-file: 3

**Comment by Feramance** [comment]
Can you please attach looks? Or is nothing at all working? Any error messages? 

Thanks

**Comment by LazerDickMcCheese** [comment]
Sorry, but this is all of the info I have to give. The container doesn't stay active enough to generate a log at all

**Comment by Feramance** [comment]
For the sake of testing, please try the following:

```
qbitrr:
    image: feramance/qbitrr:latest
```

**Comment by LazerDickMcCheese** [comment]
It start/stopped, then pumped this out:

14/08/2024 09:51 pm | NameError: name 'CONFIG' is not defined | stderr
14/08/2024 09:51 pm | CONFIG.get("Settings.FFprobeAutoUpdate", fallback=True) | stderr
14/08/2024 09:51 pm | File "/usr/local/lib/python3.10/site-packages/qBitrr/config.py", line 109, in <module> | stderr
14/08/2024 09:51 pm | from qBitrr.config import ( | stderr
14/08/2024 09:51 pm | File "/usr/local/lib/python3.10/site-packages/qBitrr/logger.py", line 9, in <module> | stderr
14/08/2024 09:51 pm | import qBitrr.logger  # noqa | stderr
14/08/2024 09:51 pm | File "/usr/local/lib/python3.10/site-packages/qBitrr/__init__.py", line 4, in <module> | stderr
14/08/2024 09:51 pm | __import__(pkg_name) | stderr
14/08/2024 09:51 pm | File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details | stderr
14/08/2024 09:51 pm | mod_name, mod_spec, code = _get_module_details(mod_name, _Error) | stderr
14/08/2024 09:51 pm | File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main | stderr
14/08/2024 09:51 pm | Traceback (most recent call last): | stderr
14/08/2024 09:51 pm | STARTING QBITRR | stdout
14/08/2024 09:51 pm | Rename it to "config.toml" then edit it and restart the container | stdout
14/08/2024 09:51 pm | 'config.rename_me.toml' has been generated | stdout
14/08/2024 09:51 pm | New config file has been saved to "/config/config.rename_me.toml" | stdout
14/08/2024 09:51 pm | config.toml has not been found

**Comment by Feramance** [comment]
Ok, so now add:

```
volumes:
  - /path/to/appdata/qbitrr:/config
```

Run it again, then rename the config file generated and change any values required within it

**Comment by Feramance** [comment]
Have you managed to get anywhere? @LazerDickMcCheese

**Comment by LazerDickMcCheese** [comment]
Long story short, changed hardware and had to do a full setup again so I was out of commission for a few days. I just set this up again, I'm getting _many_ errors about "parser.py" Do you want the logs?

**Comment by Feramance** [comment]
Hi, yes. Send trace logs and config please, ideally in a zip

**Comment by LazerDickMcCheese** [comment]
[qbitrr.zip](https://github.com/user-attachments/files/16926265/qbitrr.zip)

**Comment by Feramance** [comment]
[config.zip](https://github.com/user-attachments/files/16928870/config.zip)
Try this config as you didn't pass the correct value types. To make sure the TOML is valid I suggest using VSCode with the following extension installed: Name: Even Better TOML - https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml

**Comment by LazerDickMcCheese** [comment]
It's been a while since I looked at those files, I just realized they have my APIs and passwords in them. Would you mind deleting the ones you uploaded as well? So we have progress, qBitrr isn't stuck restarting. It's currently failing to connect to my Radarr and Sonarr instances, but those are the only errors.

**Comment by LazerDickMcCheese** [comment]
[logs.zip](https://github.com/user-attachments/files/16948191/logs.zip)

Thank you for your help

**Comment by LazerDickMcCheese** [comment]
I believe that fixed it! Strange, qbit works without http:// in front of the address so I would've never thought to try that. Thank you again for your help.

**Comment by LazerDickMcCheese** [comment]
qbitrr added tags to my qbit, so I assumed it was working. Fast forward a few days and nothing has been tagged (some of them should have been due to the config settings). So I stopped the container, checked the config.toml, and restarted the container. It's back to restarting continuously.

As a side note, qbitrr says it doesn't have permissions to its config folder if I set the YAML to the UID I usually use for docker containers despite having read/write permissions.

[qbitrr.zip](https://github.com/user-attachments/files/17008613/qbitrr.zip)

**Comment by Feramance** [comment]
If you're on a linux system, I suggest first trying to run `chmod -R 777 /path/to/qbitrr/data`, and see how that goes

**Comment by LazerDickMcCheese** [comment]
I entered the command, rebuilt the container, and it's still giving the "AttributeError: 'String' object has no attribute 'get'" error in the log and restart-looping

**Comment by Feramance** [comment]
I'll need logs again please

**Comment by LazerDickMcCheese** [comment]
When I start the container, only 2 of the logs write. "Category exists without save path" The arrs have been working just fine, so I don't know which path it's talking about.

 "[qbitrr.zip](https://github.com/user-attachments/files/17038505/qbitrr.zip)

**Comment by Feramance** [comment]
Can you run `chmod -R 777 /path/to/qBitrr/config` and try running it again? It should produce a few more logs than just that. 

Also check docker logs by running `docker logs qBitrr` in a terminal to check what else is being outputted, sometimes some things aren't captured with the file logs.

**Comment by LazerDickMcCheese** [comment]
[qbitrr.txt](https://github.com/user-attachments/files/17172122/qbitrr.txt)

**Comment by Feramance** [comment]
Ok, I'll work on fixing this, I see the problem now. In the meantime send over your config, I'll edit it slightly and send it back so you can have a working config

**Comment by LazerDickMcCheese** [comment]
Thank you for your help, you've been very kind. Did I break something? I'm lost here

[config.zip](https://github.com/user-attachments/files/17176767/config.zip)

**Comment by Feramance** [comment]
[config.zip](https://github.com/user-attachments/files/17185696/config.zip)
Use this config, the issue is the trackers, I'll look into it but you can use qBitrr in the meantime

**Comment by LazerDickMcCheese** [comment]
It's definitely working now! About 600 stalled downloads corrected themselves, and my NAS has been purring ever since. On behalf of everyone using my server, thank you for your help

**Comment by Feramance** [comment]
Very happy to hear, though I'm leaving this open to remind myself to check the trackers issue you had

**Comment by Feramance** [comment]
Hi @LazerDickMcCheese, recent fix was found by another user regarding trackers. Maybe you'd like to test them again?

**Comment by LazerDickMcCheese** [comment]
I love a good, simple fix! As far as I can tell, qBitrr is functioning as intended now. The new container has been running for a few minutes and the logs are moving incredibly fast, so far no errors.

**Comment by Feramance** [comment]
Excellent to hear, should you have any further issues, let me know
