### ISSUE TITLE
CONFIG Name error

### ISSUE THREAD

**Issue by TheRealKraken** [Feramance/qBitrr#111]
Tried starting qBitrr in ubuntu, when i start it i get the following error:

```
New config file has been saved to "/root/.config/config.rename_me.toml"
'config.rename_me.toml' has been generated
Rename it to "config.toml" then edit it and restart the container
STARTING QBITRR
Traceback (most recent call last):
  File "/usr/local/bin/qbitrr", line 5, in <module>
    from qBitrr.main import run
  File "/usr/local/lib/python3.10/dist-packages/qBitrr/__init__.py", line 4, in <module>
    import qBitrr.logger  # noqa
  File "/usr/local/lib/python3.10/dist-packages/qBitrr/logger.py", line 9, in <module>
    from qBitrr.config import (
  File "/usr/local/lib/python3.10/dist-packages/qBitrr/config.py", line 109, in <module>
    CONFIG.get("Settings.FFprobeAutoUpdate", fallback=True)
NameError: name 'CONFIG' is not defined
```

Not exactly sure where to go from here :/

**Comment by TheRealKraken** [comment]
simply user error
