### ISSUE TITLE
Unexpected APIError from qBitTorrent

### ISSUE THREAD

**Issue by VicePrez** [Feramance/qBitrr#120]
Getting `Unexpected APIError from qBitTorrent` in the logs. Let me know if you require any further info.

**CONFIG**

[config.txt](https://github.com/user-attachments/files/17401896/config.txt)

**LOGS**

```
[2024-10-16 15:41:10] [pid:       9][tid:22831867571072] INFO    : qBitrr.Sonarr-TV  : Deleting Stale torrent: Stalled State | [Progress: 0%][Added On: 2024-10-13 14:14:40][Availability: 0%][Time Left: 100 days, 0:00:00][Last active: 2024-10-13 14:14:40] | [TorrentState.METADATA_DOWNLOAD] | REDACTED (REDACTED)
[2024-10-16 15:41:14] [pid:       9][tid:22831867571072] DEBUG   : qBitrr.Sonarr-TV  : Deleting from queue: REDACTED, [Blocklisted][Blocklisting:True][Remove from client:True]
[2024-10-16 15:41:14] [pid:       9][tid:22831867571072] NOTICE  : qBitrr.Sonarr-TV  : Re-Searching series: REDACTED | [tvdbId=REDACTED|id=REDACTED]
[2024-10-16 15:41:14] [pid:       9][tid:22831867571072] DEBUG   : qBitrr.Sonarr-TV  : Folder Cleanup: tv
[2024-10-16 15:41:15] [pid:      13][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Recheck: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:15] [pid:      12][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Failed: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:15] [pid:       8][tid:22831867571072] DEBUG   : qBitrr.Sonarr-TV  : Current year 1949
[2024-10-16 15:41:19] [pid:       9][tid:22831867571072] DEBUG   : qBitrr.Utils      : Successfully connected to dns.google.com
[2024-10-16 15:41:20] [pid:      12][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Failed: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:20] [pid:      13][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Recheck: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:21] [pid:      11][tid:22831867571072] ERROR   : qBitrr.Radarr-1080: The qBittorrent API returned an unexpected error
[2024-10-16 15:41:21] [pid:      11][tid:22831867571072] DEBUG   : qBitrr.Radarr-1080: Unexpected APIError from qBitTorrent
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 3783, in _get_torrent_important_trackers
    current_trackers = {i.url for i in torrent.trackers if hasattr(i, "url")}
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/torrents.py", line 277, in trackers
    return self._client.torrents_trackers(torrent_hash=self._torrent_hash)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/decorators.py", line 117, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/torrents.py", line 1430, in torrents_trackers
    return self._post(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 390, in _post
    return self._request_manager(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 542, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 773, in _handle_error_responses
    raise NotFound404Error(error_message)
qbittorrentapi.exceptions.NotFound404Error: Torrent hash(es): REDACTED
[2024-10-16 15:41:21] [pid:      11][tid:22831867571072] CRITICAL: qBitrr.Radarr-1080: Failed to connected to qBit client, sleeping for 0:05:00
[2024-10-16 15:41:23] [pid:       8][tid:22831867571072] DEBUG   : qBitrr.Sonarr-TV  : Updating database entry | REDACTED............................................. | S23E003 [Searched:False][Upgrade:False][QualityMet:False][CustomFormatMet:False]
[2024-10-16 15:41:25] [pid:      13][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Recheck: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:25] [pid:      12][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Failed: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:25] [pid:       8][tid:22831867571072] INFO    : qBitrr.Sonarr-TV  : Started updating database
[2024-10-16 15:41:29] [pid:       8][tid:22831867571072] DEBUG   : qBitrr.Sonarr-TV  : Updating database entry | REDACTED........................................... [Searched:False][Upgrade:False]
[2024-10-16 15:41:29] [pid:       8][tid:22831867571072] NOTICE  : qBitrr.Sonarr-TV  : Starting Request search
[2024-10-16 15:41:30] [pid:      13][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Recheck: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:30] [pid:      12][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Failed: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:30] [pid:       8][tid:22831867571072] NOTICE  : qBitrr.Sonarr-TV  : Started updating database with Overseerr request entries.
[2024-10-16 15:41:32] [pid:       9][tid:22831867571072] DEBUG   : qBitrr.Utils      : Successfully connected to one.one.one.one
[2024-10-16 15:41:35] [pid:      13][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Recheck: No downloads in category, sleeping for 0:00:05
[2024-10-16 15:41:35] [pid:      12][tid:22831867571072] DEBUG   : qBitrr.Qbitrr_Failed: No downloads in category, sleeping for 0:00:05
```

**Comment by Feramance** [comment]
Can you send a larger log file?

**Comment by Feramance** [comment]
Closing issue due to inactivity

**Comment by PhattestMattest** [comment]
Hello,

I am having a similar issue and can provide a longer log.

[config.txt](https://github.com/user-attachments/files/17741015/config.txt)

[log.txt](https://github.com/user-attachments/files/17741016/log.txt)

**Comment by Feramance** [comment]
When running in debug or trace logging, yes there are sometimes errors from qbittorrent, mainly due to volume of calls or bad data returned, so these are expected and handled
