### ISSUE TITLE
AttributeError in Headless Mode

### ISSUE THREAD

**Issue by Chesyre** [Feramance/qBitrr#127]
When running the program in headless mode, the following error occurs due to an attempt to access torrent_categories from the qBittorrent client, which is not available in this mode:

`AttributeError: 'NoneType' object has no attribute 'torrent_categories'`

Error Traceback:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/qBitrr/main.py", line 250, in <module>
    run()
  File "/usr/local/lib/python3.10/site-packages/qBitrr/main.py", line 209, in run
    manager = qBitManager()
  File "/usr/local/lib/python3.10/site-packages/qBitrr/main.py", line 126, in __init__
    self.arr_manager = ArrManager(self).build_arr_instances()
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 5313, in build_arr_instances
    managed_object = Arr(name, self, client_cls=call_cls)
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 109, in __init__
    categories = self.manager.qbit_manager.client.torrent_categories.categories
AttributeError: 'NoneType' object has no attribute 'torrent_categories'
```

config sample:

```toml
[Settings]
ConsoleLevel = "INFO"
Logging = true
CompletedDownloadFolder = "/completed_downloads"
FreeSpace = "-1"
AutoPauseResume = false
NoInternetSleepTimer = 15
LoopSleepTimer = 5
SearchLoopDelay = -1
FailedCategory = "failed"
RecheckCategory = "recheck"
Tagless = true
IgnoreTorrentsYoungerThan = 300
PingURLS = ["one.one.one.one", "dns.google.com"]
FFprobeAutoUpdate = true

[qBit]
Disabled = true
Host = ""
Port = ""
UserName = ""
Password = ""

[Sonarr-TV]
Managed = true
URI = "http://sonarr:8989"
APIKey = "****"
Category = "sonarr"
ReSearch = true
importMode = "Auto"
RssSyncTimer = 5
RefreshDownloadsTimer = 5
ArrErrorCodesToBlocklist = ["Not a preferred word upgrade for existing episode file(s)", "Not an upgrade for existing episode file(s)", "Unable to determine if file is a sample"]

[Sonarr-TV.EntrySearch]
SearchMissing = true
AlsoSearchSpecials = false
SearchLimit = 5
SearchByYear = true
SearchInReverse = false
SearchRequestsEvery = 300
DoUpgradeSearch = true
QualityUnmetSearch = true
CustomFormatUnmetSearch = true
ForceMinimumCustomFormat = true
SearchAgainOnSearchCompletion = true
UseTempForMissing = false
MainQualityProfile = "1080p"
TempQualityProfile = "1080p"
SearchBySeries = true
PrioritizeTodaysReleases = true

[Sonarr-TV.EntrySearch.Ombi]
SearchOmbiRequests = false
OmbiURI = "CHANGE_ME"
OmbiAPIKey = "CHANGE_ME"
ApprovedOnly = true


[Sonarr-TV.EntrySearch.Overseerr]
SearchOverseerrRequests = false
OverseerrURI = ""
OverseerrAPIKey = ""
ApprovedOnly = true
Is4K = false

[Sonarr-TV.Torrent]
CaseSensitiveMatches = false
FolderExclusionRegex = ["\\bextras?\\b", "\\bfeaturettes?\\b", "\\bsamples?\\b", "\\bscreens?\\b", "\\bnc(ed|op)?(\\\\d+)?\\b"]
FileNameExclusionRegex = ["\\bncop\\\\d+?\\b", "\\bnced\\\\d+?\\b", "\\bsample\\b", "brarbg.com\\b", "\\btrailer\\b", "music video", "comandotorrents.com"]
FileExtensionAllowlist = []
AutoDelete = false
IgnoreTorrentsYoungerThan = 600
MaximumETA = 604800
MaximumDeletablePercentage = 0.8
DoNotRemoveSlow = true
ReSearchStalled = true
StalledDelay = 360

Trackers = []

[Sonarr-TV.Torrent.SeedingMode]
DownloadRateLimitPerTorrent = -1
UploadRateLimitPerTorrent = -1
MaxUploadRatio = -1
MaxSeedingTime = 3600
RemoveTorrent = 2
RemoveDeadTrackers = false
RemoveTrackerWithMessage = ["skipping tracker announce (unreachable)", "No such host is known", "unsupported URL protocol", "info hash is not authorized with this tracker"]
```

**Comment by Feramance** [comment]
Noted and will fix with next patch
