### ISSUE TITLE
Error on readonly database

### ISSUE THREAD

**Issue by DennisTaapken** [Feramance/qBitrr#48]
I have configured qbitrr to run on Unraid as a docker container and am using the latest version. As recommended in the manual i have mounted the sonarr.db and radarr.db files in read-only mode to the container. But i get the following error:

`Process Process-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 3885, in run_search_loop
    years, years_count = self.get_year_search()
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 3844, in get_year_search
    .execute()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 1911, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 1982, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2155, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3173, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3157, in execute_sql
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: attempt to write a readonly database
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 3885, in run_search_loop
    years, years_count = self.get_year_search()
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 3821, in get_year_search
    .execute()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 1911, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 1982, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2155, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3173, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3157, in execute_sql
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: attempt to write a readonly database
`

Why is qbitrr trying to write to the DB files ? Is it a config setting ?

**Comment by Feramance** [comment]
It's not trying to write to Arr DB files, it's trying to write to the DB files it creates itself. Check your permissions

**Comment by Feramance** [comment]
If you update to qBitrr v4 you will no longer need to face this issue as DB files are no longer required
