### ISSUE TITLE
Issue when getting queue from sonarr

### ISSUE THREAD

**Issue by JacksonDCollins** [Feramance/qBitrr#53]
Hi, intermittently and randomly (and for some reason, I'm not able to reproduce it on my local machine), the script will error out when pulling the queue from sonarr

```[2024-01-17 22:39:11] [pid:       8][tid:140560042310528] ERROR   : qBitrr.Sonarr-TV  : 'list' object has no attribute 'get'

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2849, in process_torrents

    self.refresh_download_queue()

  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 3985, in refresh_download_queue

    self.queue = self.get_queue()

  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 4037, in get_queue

    res = res.get("records", [])

AttributeError: 'list' object has no attribute 'get'
```

For some reason res is a list and not a dict object.

This is on v4.1.2

**Comment by Feramance** [comment]
A potential fix will be included in the next release, meanwhile you can ignore this error and qBitrr will continue working as expected
