### ISSUE TITLE
Internal Server Error when blocklisting torrents on Radarr/Sonarr

### ISSUE THREAD

**Issue by DeadPackets** [Feramance/qBitrr#64]
Whenever qBitrr tries to blocklist a stalled torrent on any *Arr app, it generates an error. Logs below:

```
qbitrr-1  | [2024-02-28 02:27:29] [pid:      10][tid:140329628478336] INFO    : qBitrr.Radarr-1080 : Deleting Stale torrent: Stalled State | [Progress: 0%][Added On: 2024-01-30 21:21:20][Availability: 0%][Time Left: 100 days, 0:00:00][Last active: 2024-01-30 21:21:20] | [TorrentState.METADATA_DOWNLOAD] | The.Wall.2017.1080p.BluRay.x265.HEVC.AAC.mkv (0451b7ffaf4dfa78ec17ea5aa69b24cb60cf30f7)
qbitrr-1  | [2024-02-28 02:27:29] [pid:      10][tid:140329628478336] TRACE   : qBitrr.Radarr-1080 : Config Settings for torrent [Poor Things (2023) [1080p] [WEBRip] [5.1] [YTS.MX]]: {'ratio_limit': -5, 'seeding_time_limit': -5, 'dl_limit': -5, 'up_limit': -5, 'super_seeding': False, 'max_eta': 36000}
qbitrr-1  | [2024-02-28 02:27:29] [pid:      10][tid:140329628478336] TRACE   : qBitrr.Radarr-1080 : Torrent Settings for torrent [Poor Things (2023) [1080p] [WEBRip] [5.1] [YTS.MX]]: {'ratio_limit': 1, 'seeding_time_limit': -5, 'dl_limit': -5, 'up_limit': -5, 'super_seeding': False}
qbitrr-1  | [2024-02-28 02:27:29] [pid:      10][tid:140329628478336] TRACE   : qBitrr.Radarr-1080 : Torrent [Poor Things (2023) [1080p] [WEBRip] [5.1] [YTS.MX]]: Leave Alone (allow seeding): True, Max ETA: 36000, State[TorrentState.STALLED_UPLOAD]
qbitrr-1  | [2024-02-28 02:27:29] [pid:      10][tid:140329628478336] TRACE   : qBitrr.Radarr-1080 : Torrent State: Completed | Allowing Seeding | [Progress: 100%][Added On: 2024-02-27 23:08:39][Availability: -100%][Time Left: 100 days, 0:00:00][Last active: 2024-02-28 02:14:03] | [TorrentState.STALLED_UPLOAD] | Poor Things (2023) [1080p] [WEBRip] [5.1] [YTS.MX] (5b2b689438bf124d09289f1872f0031fabc7dde8)
qbitrr-1  | [2024-02-28 02:27:29] [pid:      10][tid:140329628478336] DEBUG   : qBitrr.Radarr-1080 : Blocklisting: 0451B7FFAF4DFA78EC17EA5AA69B24CB60CF30F7 (Deleted)
qbitrr-1  | [2024-02-28 02:27:29] [pid:      10][tid:140329628478336] ERROR   : qBitrr.Radarr-1080 : Internal Server Error: The method or operation is not implemented.
qbitrr-1  | Traceback (most recent call last):
qbitrr-1  |   File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2976, in process_torrents
qbitrr-1  |     self.process()
qbitrr-1  |   File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2925, in process
qbitrr-1  |     self._process_failed()
qbitrr-1  |   File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 1033, in _process_failed
qbitrr-1  |     self._process_failed_individual(
qbitrr-1  |   File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 835, in _process_failed_individual
qbitrr-1  |     self.delete_from_queue(id_=entry, blacklist=True)
qbitrr-1  |   File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2531, in delete_from_queue
qbitrr-1  |     res = self.client.del_queue(id_, remove_from_client, blacklist)
qbitrr-1  |   File "/usr/local/lib/python3.10/site-packages/pyarr/base.py", line 505, in del_queue
qbitrr-1  |     return self._delete(f"queue/{id_}", self.ver_uri, params=params)
qbitrr-1  |   File "/usr/local/lib/python3.10/site-packages/pyarr/request_handler.py", line 193, in _delete
qbitrr-1  |     response = _process_response(res)
qbitrr-1  |   File "/usr/local/lib/python3.10/site-packages/pyarr/request_handler.py", line 248, in _process_response
qbitrr-1  |     raise PyarrServerError(
qbitrr-1  | pyarr.exceptions.PyarrServerError: Internal Server Error: The method or operation is not implemented.
```

**Comment by Feramance** [comment]
Please attach your configs

**Comment by Feramance** [comment]
Has this happened again or just the one time?

**Comment by Feramance** [comment]
Can you please confirm this is still an issue following the latest version?

**Comment by DeadPackets** [comment]
Still an issue, now just geting `Connection Error` instead of the entire Exception block.

**Comment by Feramance** [comment]
Is the connection error happening with every call or sometimes, other times no?

**Comment by Feramance** [comment]
Closing as non-issue
