### ISSUE TITLE
Container keeps crashing - AttributeError: 'NoneType' object has no attribute 'torrents_create_tags'

### ISSUE THREAD

**Issue by radh21301** [Feramance/qBitrr#92]
I feel like I am doing something wrong with my configuration (attached in the end), but unable to figure it out. I get the following error error. Seems that it want a tag named 'torrents_create_tags', but I cant find any reference to that in the example config.
```
07/08/2024, 02:40:15 PM, [2024-07-08 14:40:15] [pid:       1][tid:22480104070016] INFO : qBitrr : Starting qBitrr: Version: 4.8.0-fd32445.
07/08/2024, 02:40:15 PM, Traceback (most recent call last):
07/08/2024, 02:40:15 PM,   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
07/08/2024, 02:40:15 PM,     return _run_code(code, main_globals, None,
07/08/2024, 02:40:15 PM,   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
07/08/2024, 02:40:15 PM,     exec(code, run_globals)
07/08/2024, 02:40:15 PM,   File "/usr/local/lib/python3.10/site-packages/qBitrr/main.py", line 247, in <module>
07/08/2024, 02:40:15 PM,     run()
07/08/2024, 02:40:15 PM,   File "/usr/local/lib/python3.10/site-packages/qBitrr/main.py", line 206, in run
07/08/2024, 02:40:15 PM,     manager = qBitManager()
07/08/2024, 02:40:15 PM,   File "/usr/local/lib/python3.10/site-packages/qBitrr/main.py", line 122, in __init__
07/08/2024, 02:40:15 PM,     self.arr_manager = ArrManager(self).build_arr_instances()
07/08/2024, 02:40:15 PM,   File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 5284, in build_arr_instances
07/08/2024, 02:40:15 PM,     managed_object = Arr(name, self, client_cls=call_cls)
07/08/2024, 02:40:15 PM,   File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 511, in __init__
07/08/2024, 02:40:15 PM,     self.manager.qbit_manager.client.torrents_create_tags(
07/08/2024, 02:40:15 PM, AttributeError: 'NoneType' object has no attribute 'torrents_create_tags'
```

-----------------------------------

**Additional info:**
[qbitrr_config.txt](https://github.com/user-attachments/files/16133374/qbitrr_config.txt)
OS: Unraid
Installed via docker
qBitrr: Version: 4.8.0-fd32445

**My use case:**
I only need qbitrr to keep refreshing radarr, sonarr, and overseer to search for missing/upgradable content. I do not need qbitrr to manage my torrent client.

Let me know if I can help get more info to debug this.

**Comment by Feramance** [comment]
Hi, please give `feramance/qbitrr:pr-92` a try and let me know how it goes

**Comment by radh21301** [comment]
I tried it by setting the image in the docker compose to what you mentioned. Is this how I do it?
```
image: feramance/qbitrr:pr-92
```

But getting this error when I run a docker compose up
```
qbitrr Error manifest for feramance/qbitrr:pr-92 not found: manifest unknown: manifest unknown                                   1.0s 
Error response from daemon: manifest for feramance/qbitrr:pr-92 not found: manifest unknown: manifest unknown
```

**Comment by Feramance** [comment]
My apologies, I meant `feramance/qbitrr:pr-92`

**Comment by radh21301** [comment]
Looks like that worked! Thank you!

**Comment by Feramance** [comment]
Merged the changes, you can switch to the latest image again
